---
apiVersion: v1
data:
  htpasswd: GRm1sNVA5JHdueGhJT3UybDltUC5FUlhCVnBWWi4KZGV2MDI6JGFwcjEkT3p5dlo1dDMkY1ZlbkgzUURCSUxMaGxIWDRCVHRhMQpkZXYwMzokYXByMSQwQVIzNG8veiRGVW55MDRVcWE1NUh4d2YzekhPSkcvCmRldjA0OiRhcHIxJEgyaWdnallhJFY5QWwzTjZPL3FMS3ozU0hoNnBFajEKZGV2MDU6JGFwcjEkMUR6NVBHZjEkTTZWdS8xb2I4akJuYk9tMFB1WjRqLwpkZXYwNjokYXByMSRHdnczNEtNUyRtWGJYUTVjNmM2Y1FGZTREZlRUY3QwCmRldjA3OiRhcHIxJDM5OWljbXY4JDZkSEl2MnhHWWtoanBTN0ouMkxTci4KZGV2MDg6JGFwcjEkbWFPVGlXTVUkNWhKaFdyV0hISDB6bnpqNHQ5am1FLgpkZXYwOTokYXByMSR5T29vUlFIaiRyUHAxcEZ3WlNLWTIvZ2lrLjFXdksxCmRldjEwOiRhcHIxJEtwQmYwbi9rJDVhN0g4RjQvTjZBdWJGLktxSUZpbTAKZGV2MTE6JGFwcjEkalZHTllIcjQkekd2OUM2SlNlMTJ2NDhpbHJNeWVUMQpkZXYxMjokYXByMSRNN0o1OFkuNyRkYjlnQko3amc4S1BOQTRSaHAxcjYwCmRldjEzOiRhcHIxJDRyL2c1MHRvJDFHdnE1VUhUTTd4YjVnb1V2d1dHVzEKZGV2MTQ6JGFwcjEkZFdQamxEY3EkVDFNS1BGRDVTaHJSWExCTVYwL0NPMApkZXYxNTokYXByMSREUjAuRnBELiQ1emhpOFFSamE0T0lobmd4U1Z3dzAvCg==
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
